// COPYRIGHT (C) HARRY CLARK 2026
// CS2_OS LAB AND TUTORIAL CONTENTS

// THIS FILE PERTAINS TOWARDS THE MAIN FUNCTIONALITY OF LAB 04

// NESTED INCLUDES  

#define EXERCISE_4_1
#include "LAB04.h"

int main(void)
{
    LAB_FILE_DISPLAY("input.txt", 512);
    return 0;
}
