// COPYRIGHT (C) HARRY CLARK 2026
// CS2_OS LAB AND TUTORIAL CONTENTS

// THE FOLLOWING FILE PERTAINS TOWARDS THE MAIN FUNCTIONALITY ENCOMPASSING
// EXERCISE 3.1.B FROM LAB_03 
//
// THE FOLLOWING IMPLEMENTATION IS ADJACENT FROM THE LAB03 FOLDER ITSELF
// TO AVOID ALL OF THE FUNCTIONALITY BECOMING OVERLY CROWDED 

#ifndef CS2_OS_LAB_03_CBUFFER_H
#define CS2_OS_LAB_03_CBUFFER_H

// SYSTEM INCLUDES

#include <stdio.h>
#include <stdlib.h>

typedef size_t UNK;

// DEFINE THE BASIS FOR HOW THE CIRCULAR BUFFER
// IS PRESENTED - THROUGH IT'S RELATED FIELDS

typedef struct
{
    int* DATA;
    UNK CAPACITY;
    UNK WRITE;
    UNK COUNT;

} CIRCULAR_BUFFER;

        #define         BUFFER_DATA         CB->DATA;
        #define         BUFFER_CAP          CB->CAPACITY;
        #define         BUFFER_WRITE        CB->WRITE;
        #define         BUFFER_COUNT        CB->COUNT;

        extern CIRCULAR_BUFFER CB;

#endif