// COPYRIGHT (C) HARRY CLARK 2026
// CS2_OS LAB AND TUTORIAL CONTENTS

// THIS FILE PERTAINS TOWARDS THE MAIN FUNCTIONALITY OF LAB 03

// SYSTEM INCLUDES

#include <stdio.h>

int
main(void)
{
    return 0;
}