// COPYRIGHT (C) HARRY CLARK 2026
// CS2_OS LAB AND TUTORIAL CONTENTS

// THIS FILE PERTAINS TOWARDS THE MAIN FUNCTIONALITY OF LAB 03

#define     EXERCISE_3_4

// NESTED INCLUDES

#include "LAB03.h"

int
main(void)
{
    LAB_OUTPUT("HELLO, WORLD\n");
    return 0;
}
